version: 2
jobs:
    Build:
        docker:
            - image: circleci/node:12

        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-

            - run:
                name: Install dependencies
                command: yarn install

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
        
            - run:
                name: Build Typescript source code
                command: yarn build
                when: always
    Lint:
        docker:
            - image: circleci/node:12
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-
            - run:
                name: Install dependencies
                command: yarn install
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                name: Lint source with ESLint
                command: |
                    yarn lint --format junit --output-file ~/reports/eslint.xml
                    yarn lint:test --format junit --output-file reports/eslint/lint-result.xml
                when: always
            - store_test_results:
                path: reports/eslint
    
            - store_artifacts:
                path: reports/eslint
    Tests:
        docker:
            - image: circleci/node:12
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-
            - run:
                name: Install dependencies
                command: yarn install
            - run:
                name: Install JUnit test reporter
                command: yarn add --dev jest-junit
            - run:
                name: Run tests with JUnit as reporter
                command: yarn test --ci --runInBand --reporters=default --reporters=jest-junit --coverage
                environment:
                    JEST_JUNIT_OUTPUT_DIR: "reports/jest/js-test-results.xml"
            - store_test_results:
                path: reports/jest
            - store_artifacts:
                path: reports/jest
            - store_artifacts:
                path: coverage
                destination: coverage
    
workflows:
    version: 2
    test_and_lint:
        jobs:
            - Build
            - Lint:
                requires:
                    - Build
            - Tests:
                requires:
                    - Build
                    